---
- name: Copy file from S3 bucket
  hosts: localhost
  gather_facts: no
  connection: local
 

  tasks:
  - name: Install boto3 and botocore Python packages
    pip:
      name: boto3
      state: present
    

  - name: Copy file from S3 bucket
     S3:
      s3_bucket_name: ansible-abc
      s3_object_key: f1.txt
      local_file_path: C:\Users\ENAGESWA\Downloads\Test_s3
      aws_access_key: "AKIAR2PRKHAI4LL2HGNH"
      aws_secret_key: "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"
      
