---
- name: Copy file from S3 bucket
  hosts: all
  become: root
  gather_facts: no

 

  tasks:
  - name: Install boto3 and botocore Python packages
    pip:
      name: boto3
      state: present
    

  - name: Copy file from S3 bucket
    s3:
      bucket: ansible-abc
      object: s3://ansible-abc/f1.txt
      dest: /root/test1
      mode: get
      
      
