---
  - name: Playbook
    hosts: all
    become: yes
    become_method: sudo
    tasks:
      - name: ensure apache is at the latest version
        dnf:
          name: httpd
          state: latest
        become_user: root
        
      - name: ensure apache is running
        service:
          name: httpd
          state: started
        become_user: root
